"""
build_feasibility_matrix.py – Create or update the five-layer feasibility
matrix for the GridSpark AI Lane County prototype.

Run this first to initialize outputs/feasibility_matrix.csv and
outputs/feasibility_matrix.md, then re-run each verify_*.py script to fill
in individual layer statuses.
"""

import sys
import csv
import logging
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
from config import FEASIBILITY_CSV, FEASIBILITY_MD, COUNTY, FIRE_NAME

logging.basicConfig(level=logging.INFO, format="%(levelname)s: %(message)s")
log = logging.getLogger(__name__)

COLUMNS = [
    "target_county",
    "event",
    "hifld_grid_status",
    "fpa_fod_ignition_status",
    "mtbs_wfigs_boundary_status",
    "sentinel2_prefire_status",
    "noaa_isd_status",
    "notes",
    "overall_status",
]

DEFAULT_ROW = {
    "target_county": COUNTY,
    "event": FIRE_NAME,
    "hifld_grid_status": "To verify",
    "fpa_fod_ignition_status": "To verify",
    "mtbs_wfigs_boundary_status": "To verify",
    "sentinel2_prefire_status": "To verify",
    "noaa_isd_status": "To verify",
    "notes": "Initial scaffold — run verify_*.py scripts to populate.",
    "overall_status": "To verify",
}

STATUS_FIELDS = [
    "hifld_grid_status",
    "fpa_fod_ignition_status",
    "mtbs_wfigs_boundary_status",
    "sentinel2_prefire_status",
    "noaa_isd_status",
]


def _derive_overall(row: dict) -> str:
    statuses = [row[f] for f in STATUS_FIELDS]
    if all(s.startswith("Pass") for s in statuses):
        return "FEASIBLE"
    if any(s == "Fail" for s in statuses):
        return "NOT FEASIBLE"
    passes = sum(1 for s in statuses if s.startswith("Pass"))
    if passes == len(statuses) - 1:
        return f"4/5 Pass – Sentinel-2 pending GEE auth"
    if any(s == "To verify" for s in statuses):
        return "Pending"
    return "Manual Check Required"


def load_matrix() -> dict:
    """Load existing matrix row or return defaults."""
    if FEASIBILITY_CSV.exists():
        with open(FEASIBILITY_CSV, newline="") as f:
            reader = csv.DictReader(f)
            rows = list(reader)
            if rows:
                return rows[0]
    return dict(DEFAULT_ROW)


def save_matrix(row: dict):
    """Write CSV and Markdown representations."""
    FEASIBILITY_CSV.parent.mkdir(parents=True, exist_ok=True)
    row["overall_status"] = _derive_overall(row)

    # --- CSV ---
    with open(FEASIBILITY_CSV, "w", newline="") as f:
        writer = csv.DictWriter(f, fieldnames=COLUMNS)
        writer.writeheader()
        writer.writerow(row)

    # --- Markdown ---
    _write_markdown(row)
    log.info("Feasibility matrix saved to %s", FEASIBILITY_CSV)


def _write_markdown(row: dict):
    status_icon = {
        "Pass": "✅",
        "Fail": "❌",
        "Manual Check": "⚠️",
        "To verify": "🔲",
        "FEASIBLE": "✅",
        "NOT FEASIBLE": "❌",
        "Pending": "🔲",
        "Manual Check Required": "⚠️",
    }

    def icon(val):
        for k, v in status_icon.items():
            if str(val).startswith(k):
                return f"{v} {val}"
        return val

    lines = [
        "# GridSpark AI – Five-Layer Feasibility Matrix",
        "",
        f"**County:** {row['target_county']}  ",
        f"**Event:** {row['event']}  ",
        f"**Overall status:** {icon(row['overall_status'])}",
        "",
        "| Layer | Status | Notes |",
        "|---|---|---|",
        f"| HIFLD Transmission Lines | {icon(row['hifld_grid_status'])} | Bulk power infrastructure only; not distribution poles |",
        f"| FPA-FOD Ignition Points | {icon(row['fpa_fod_ignition_status'])} | Approximate labels; use buffer sensitivity |",
        f"| MTBS / WFIGS Fire Perimeter | {icon(row['mtbs_wfigs_boundary_status'])} | Holiday Farm 2020 burn boundary |",
        f"| Sentinel-2 Pre-fire Imagery | {icon(row['sentinel2_prefire_status'])} | 10–20 m NDVI/NDMI/NBR, 2020-08-20 to 2020-09-06 |",
        f"| NOAA ISD Weather | {icon(row['noaa_isd_status'])} | Hourly wind/temp/RH near ignition |",
        "",
        "## Full row",
        "",
        "```",
    ]
    for k, v in row.items():
        lines.append(f"{k}: {v}")
    lines += ["```", "", f"*Generated by build_feasibility_matrix.py*"]

    with open(FEASIBILITY_MD, "w") as f:
        f.write("\n".join(lines))


def update_feasibility_field(field: str, status: str, notes_append: str = ""):
    """
    Update a single status field and re-save. Intended to be called from
    verify_*.py scripts. Deduplicates notes entries.
    """
    if field not in COLUMNS:
        raise ValueError(f"Unknown field: {field}")
    row = load_matrix()
    row[field] = status
    if notes_append:
        existing = row.get("notes", "")
        # Deduplicate: only append if this exact note isn't already present
        parts = [p.strip() for p in existing.split(" | ")] if existing else []
        parts = [p for p in parts if p and p != DEFAULT_ROW["notes"]]
        if notes_append not in parts:
            parts.append(notes_append)
        row["notes"] = " | ".join(parts)
    save_matrix(row)


def run():
    row = load_matrix()
    # Only reset to defaults if matrix doesn't exist yet
    if not FEASIBILITY_CSV.exists():
        row = dict(DEFAULT_ROW)
        log.info("Initializing fresh feasibility matrix.")
    else:
        log.info("Existing matrix loaded — preserving current statuses.")
    save_matrix(row)
    log.info("Overall status: %s", row["overall_status"])
    print("\nFeasibility matrix initialized at:")
    print(f"  CSV:      {FEASIBILITY_CSV}")
    print(f"  Markdown: {FEASIBILITY_MD}")
    print("\nRun verify_*.py scripts to populate individual layer statuses.")


if __name__ == "__main__":
    run()
